export enum ROUTES_PATHS {
  SIGN_IN = '/sign-in',
  FORGOT_PASSWORD = '/forgot-password',
  CREATE_NEW_PASSWORD = '/create-new-password',
  CONFIRMED_EMAIL = '/confirmed-email',
  DASHBOARD = '/',
  USERS = '/users',
  USER_SINGLE = '/users/:id',
  CLIENTS = '/clients',
  CLIENT_SINGLE = '/client/:id',
  STATIONS = '/stations',
  STATION_SINGLE = '/stations/:id',
  DISTRICTS = '/districts',
  DISTRICT_SINGLE = '/districts/:id',
  REGIONS = '/regions',
  BIDS = '/bids',
  BID_SINGLE = '/bids/:id',
  REPORTS = '/reports',
  ACCOUNT = '/account',
}
